Add code to task2
2bigballs/csdt2324ki49melnykiv18 pull request #2
Opened 2023-10-27 18:06 UTC by 2bigballs

2023-10-27 19:45 UTC, andrii-s-spitzer-lpnu-ua requested changes

2023-10-27 19:45 UTC, andrii-s-spitzer-lpnu-ua commented on Arduino lab2/Arduino lab2/obj/Debug/net7.0/refint/Arduino lab2.dll
Please remove binary files. Git can not manage binary files.

2023-11-06 13:31 UTC, 2bigballs commented on Arduino lab2/Arduino lab2/obj/Debug/net7.0/refint/Arduino lab2.dll
add .gitignore and delete binary files

2023-11-06 18:36 UTC, andrii-s-spitzer-lpnu-ua approved these changes

2023-11-06 23:20 UTC, merged